/* Node test harness — exercises the REAL worker.js + converter.js logic
   (no browser) to validate the conversion output. Not shipped. */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.join(__dirname, "..");

// ---- 1. run the real worker.js against a known 3x2 image ----------
// pixels: row0 = red(255,0,0,255), transparent(0,0,0,0), white(255,255,255,255)
//         row1 = #1a1a1a, partial-alpha blue(0,0,255,128), green(0,255,0,255)
const W = 3, H = 2;
const data = new Uint8ClampedArray([
  255, 0, 0, 255,   0, 0, 0, 0,     255, 255, 255, 255,
  26, 26, 26, 255,  0, 0, 255, 128, 0, 255, 0, 255,
]);

function runWorker(opts) {
  const sandbox = { self: {}, Uint8ClampedArray, Math, Array, postMessageLog: [] };
  sandbox.self.postMessage = (m) => sandbox.postMessageLog.push(m);
  const code = fs.readFileSync(path.join(root, "js/worker.js"), "utf8");
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox);
  sandbox.self.onmessage({
    data: Object.assign(
      { type: "build", data: data.buffer.slice(0), width: W, height: H,
        blockSize: 1, format: "rgba", method: "boxshadow", reduce: 0, alphaThreshold: 0 },
      opts
    ),
  });
  return sandbox.postMessageLog;
}

const log = runWorker({ format: "rgba" });
const done = log.find((m) => m.type === "done");
const progresses = log.filter((m) => m.type === "progress").map((m) => m.pct);
console.log("=== worker (rgba) ===");
console.log("progress ticks:", progresses.join(","));
console.log("kept count   :", done.count, "(expected 5 — transparent pixel skipped)");
console.log("box-shadow value:\n  " + done.value.replace(/\n/g, "\n  "));

// hex with short-collapse test
const hexDone = runWorker({ format: "hex" }).find((m) => m.type === "done");
console.log("\n=== worker (hex) ===");
console.log(hexDone.value);
console.log("(expect #1a1a1a NOT collapsed, #fff collapsed for white, #f00 for red)");

// ---- 2. run the real converter._assemble ---------------------------
const sandbox2 = {
  window: {},
  document: { createElement: () => ({ getContext: () => ({}) }) },
  performance: { now: () => 0 },
  Blob: function (parts) { this.size = Buffer.byteLength(parts.join("")); },
  URL: { createObjectURL: () => "", revokeObjectURL: () => {} },
  Image: function () {},
  console,
};
sandbox2.global = sandbox2;
vm.createContext(sandbox2);
vm.runInContext(fs.readFileSync(path.join(root, "js/converter.js"), "utf8"), sandbox2);
const Converter = sandbox2.window.Converter;
Converter.settings.format = "rgba";
Converter.settings.blockSize = 1;
const result = Converter._assemble(
  { type: "done", method: "boxshadow", value: done.value, count: done.count }, W, H, 12
);

// ---- 2b. parity: embedded coreBuild must match standalone worker.js -
const parity = Converter._coreBuild(
  data, W, H, 1, "rgba", "boxshadow", 0, 0, function () {}
);
const parityOk = parity.value === done.value && parity.count === done.count;
console.log("\n=== parity (coreBuild vs worker.js) ===");
console.log(parityOk ? "MATCH" : "MISMATCH\n worker.js: " + done.value + "\n coreBuild: " + parity.value);

console.log("\n=== assembled fullCss ===");
console.log(result.fullCss);
console.log("=== assembled fullHtml ===");
console.log(result.fullHtml);

// ---- 3. assertions -------------------------------------------------
const html = result.fullHtml;
const checks = [
  ["kept count is 5 (transparent skipped)", done.count === 5],
  ["progress reached 100", progresses.includes(100)],
  ["rgba preserves partial alpha", /rgba\(0,0,255,0\.50?2?\)/.test(done.value) || /rgba\(0,0,255,/.test(done.value)],
  ["hex collapses white to #fff", /#fff(\b|,)/.test(hexDone.value)],
  ["hex collapses red to #f00", /#f00(\b|,)/.test(hexDone.value)],
  ["hex keeps #1a1a1a uncollapsed", /#1a1a1a/.test(hexDone.value)],
  ["fullHtml has NO <img> tag", !/<img/i.test(html)],
  ["fullHtml has NO <script>", !/<script/i.test(html)],
  ["fullHtml contains box-shadow", /box-shadow/.test(html)],
  ["fullHtml contains the div", /class="img2css"/.test(html)],
  ["css has header comment", /Generated by img2css/.test(result.fullCss)],
  ["sizeBytes computed", result.sizeBytes > 0],
  ["coreBuild parity with worker.js", parityOk],
];
console.log("\n=== assertions ===");
let pass = 0;
checks.forEach(([name, ok]) => {
  console.log((ok ? "PASS" : "FAIL") + " — " + name);
  if (ok) pass++;
});
console.log(`\n${pass}/${checks.length} passed`);

// write the sample export so we can open it in a browser if desired
fs.writeFileSync(path.join(__dirname, "sample-output.html"), html);
console.log("wrote _test/sample-output.html");
process.exit(pass === checks.length ? 0 : 1);
